Fixed issue 258
LuposX/KonfiguratorFuerOSMDaten pull request #292
Opened 2023-03-10 17:37 UTC by FelixWeik

Data frame asks for directory paths now instead of filenames

2023-03-11 15:56 UTC, GloeStoe requested changes
The user should enter a directory when selecting a category import, if he selects OSM and geojson data he must enter osm and geojson files respectively

2023-03-11 15:56 UTC, GloeStoe commented on src/osm_configurator/view/toplevelframes/data_frame.py
> +        chosen_path: Path = self.__get_directory_path()
Why do you ask the user for a directory when selecting a cut out file? It was correct, the way it was before

2023-03-11 15:56 UTC, GloeStoe commented on src/osm_configurator/view/toplevelframes/data_frame.py
> +        chosen_path: Path = self.__get_directory_path()
Why do you ask the user for a directory when selecting a osm file?

2023-03-12 14:30 UTC, GloeStoe approved these changes

2023-03-12 14:44 UTC, ujrlh approved these changes
looks good and works

2023-03-12 14:44 UTC, ujrlh commented on src/osm_configurator/view/toplevelframes/data_frame.py
> +        print(chosen_path)
remove print statement

2023-03-12 15:30 UTC, merged