Application
LuposX/KonfiguratorFuerOSMDaten pull request #56
Opened 2023-02-12 02:32 UTC by ujrlh

I do have to fix one test tomorow, but apart from that everything should be fine.

2023-02-12 12:59 UTC, LuposX commented on src/osm_configurator/model/application/passive_project.py
> +        return Path(self.data[2][1])
magic number

2023-02-12 12:59 UTC, LuposX commented on src/osm_configurator/model/application/passive_project.py
> +        return self.data[4][1]
magic number

2023-02-12 13:16 UTC, GloeStoe commented on src/osm_configurator/model/application/application.py
> +    def create_project(self, name: str, description: str, destination: pathlib.Path) -> bool:
inheritance

2023-02-12 13:17 UTC, GloeStoe commented on src/osm_configurator/model/application/application_settings_saver.py
> +            filename = "default_project_folder.txt"
mybe don't use a .txt but a more descriptive extension

2023-02-12 13:20 UTC, GloeStoe commented on src/osm_configurator/model/application/application.py
> +from src.osm_configurator.model.application.application_settings import ApplicationSettings
don't import with from!

2023-02-12 13:20 UTC, GloeStoe commented on src/osm_configurator/model/application/application_interface.py
> +    def get_passive_project_list(self) -> list[PassiveProject]:
List is written big

2023-02-12 13:28 UTC, GloeStoe commented on src/osm_configurator/model/application/passive_project.py
> +    def __init__(self, settings_file):
typehints

2023-02-13 09:30 UTC, LuposX requested changes

2023-02-13 09:30 UTC, LuposX commented on src/osm_configurator/model/application/application_interface.py
> +    def load_project(self, destination) -> bool:
typehint

2023-02-13 09:30 UTC, LuposX commented on src/osm_configurator/model/application/application_settings_io_handler.py
> +            bool: True when building the path works, otherwise false.
wron tpyrhint

2023-02-13 09:30 UTC, LuposX commented on src/osm_configurator/model/application/passive_project.py
> +        return self.data[4][1]
still magic numbers.

2023-02-13 11:28 UTC, LuposX approved these changes

2023-02-13 11:35 UTC, merged